### ISSUE TITLE
install script not working

### ISSUE THREAD

**Issue by swornimbarahi** [sabi1125/CodeSeed#31]
```
CodeSeed % ./install.sh
./install.sh: line 3: file_to_check: command not found
./install.sh: line 4: second_file_to_check: command not found
Collecting argparse==1.4.0 (from -r requirements.txt (line 1))
  Using cached argparse-1.4.0-py2.py3-none-any.whl (23 kB)
Requirement already satisfied: pyinstaller==6.3.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from -r requirements.txt (line 2)) (6.3.0)
Requirement already satisfied: setuptools>=42.0.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from pyinstaller==6.3.0->-r requirements.txt (line 2)) (65.5.0)
Requirement already satisfied: altgraph in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from pyinstaller==6.3.0->-r requirements.txt (line 2)) (0.17.4)
Requirement already satisfied: pyinstaller-hooks-contrib>=2021.4 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from pyinstaller==6.3.0->-r requirements.txt (line 2)) (2023.11)
Requirement already satisfied: packaging>=22.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from pyinstaller==6.3.0->-r requirements.txt (line 2)) (23.2)
Requirement already satisfied: macholib>=1.8 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from pyinstaller==6.3.0->-r requirements.txt (line 2)) (1.16.3)
Installing collected packages: argparse
Successfully installed argparse-1.4.0
108 INFO: PyInstaller: 6.3.0
108 INFO: Python: 3.11.1
114 INFO: Platform: macOS-14.1.2-arm64-arm-64bit
114 INFO: wrote /Users/lanaya/Code/CodeSeed/codeseed.spec
117 INFO: Extending PYTHONPATH with paths
['/Users/lanaya/Code/CodeSeed']
169 INFO: checking Analysis
170 INFO: Building Analysis because Analysis-00.toc is non existent
170 INFO: Initializing module dependency graph...
171 INFO: Caching module graph hooks...
178 INFO: Analyzing base_library.zip ...
575 INFO: Loading module hook 'hook-heapq.py' from '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/PyInstaller/hooks'...
616 INFO: Loading module hook 'hook-encodings.py' from '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/PyInstaller/hooks'...
1390 INFO: Loading module hook 'hook-pickle.py' from '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/PyInstaller/hooks'...
2099 INFO: Caching module dependency graph...
2134 INFO: Running Analysis Analysis-00.toc
2134 INFO: Looking for Python shared library...
2136 INFO: Using Python shared library: /Library/Frameworks/Python.framework/Versions/3.11/Python
2136 INFO: Analyzing /Users/lanaya/Code/CodeSeed/codeseed.py
2148 INFO: Loading module hook 'hook-platform.py' from '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/PyInstaller/hooks'...
2162 INFO: Loading module hook 'hook-xml.py' from '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/PyInstaller/hooks'...
2181 INFO: Processing module hooks...
2333 INFO: Performing binary vs. data reclassification (3 entries)
2337 INFO: Looking for ctypes DLLs
2342 INFO: Analyzing run-time hooks ...
2343 INFO: Including run-time hook '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/PyInstaller/hooks/rthooks/pyi_rth_inspect.py'
2346 INFO: Looking for dynamic libraries
2405 INFO: Warnings written to /Users/lanaya/Code/CodeSeed/build/codeseed/warn-codeseed.txt
2410 INFO: Graph cross-reference written to /Users/lanaya/Code/CodeSeed/build/codeseed/xref-codeseed.html
2450 INFO: checking PYZ
2450 INFO: Building PYZ because PYZ-00.toc is non existent
2450 INFO: Building PYZ (ZlibArchive) /Users/lanaya/Code/CodeSeed/build/codeseed/PYZ-00.pyz
2585 INFO: Building PYZ (ZlibArchive) /Users/lanaya/Code/CodeSeed/build/codeseed/PYZ-00.pyz completed successfully.
2587 INFO: EXE target arch: arm64
2587 INFO: Code signing identity: None
2588 INFO: checking PKG
2588 INFO: Building PKG because PKG-00.toc is non existent
2588 INFO: Building PKG (CArchive) codeseed.pkg
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/PyInstaller/building/utils.py", line 272, in process_collected_binary
    osxutils.binary_to_target_arch(cached_name, target_arch, display_name=src_name)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/PyInstaller/utils/osx.py", line 347, in binary_to_target_arch
    convert_binary_to_thin_arch(filename, target_arch)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/PyInstaller/utils/osx.py", line 315, in convert_binary_to_thin_arch
    raise SystemError(f"lipo command ({cmd_args}) failed with error code {p.returncode}!\noutput: {p.stdout}")
SystemError: lipo command (['lipo', '-thin', 'arm64', '/Users/lanaya/Library/Application Support/pyinstaller/bincache00py31164bit/arm64/adhoc/no-entitlements/lib-dynload/_struct.cpython-311-darwin.so', '-output', '/Users/lanaya/Library/Application Support/pyinstaller/bincache00py31164bit/arm64/adhoc/no-entitlements/lib-dynload/_struct.cpython-311-darwin.so']) failed with error code 1!
output: xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/PyInstaller/__main__.py", line 218, in <module>
    run()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/PyInstaller/__main__.py", line 198, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/PyInstaller/__main__.py", line 69, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/PyInstaller/building/build_main.py", line 1071, in main
    build(specfile, distpath, workpath, clean_build)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/PyInstaller/building/build_main.py", line 1011, in build
    exec(code, spec_namespace)
  File "/Users/lanaya/Code/CodeSeed/codeseed.spec", line 18, in <module>
    exe = EXE(
          ^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/PyInstaller/building/api.py", line 609, in __init__
    self.pkg = PKG(
               ^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/PyInstaller/building/api.py", line 238, in __init__
    self.__postinit__()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/PyInstaller/building/datastruct.py", line 184, in __postinit__
    self.assemble()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/PyInstaller/building/api.py", line 289, in assemble
    src_name = process_collected_binary(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/PyInstaller/building/utils.py", line 297, in process_collected_binary
    raise SystemError(f"Failed to process binary {cached_name!r}!") from e
SystemError: Failed to process binary '/Users/lanaya/Library/Application Support/pyinstaller/bincache00py31164bit/arm64/adhoc/no-entitlements/lib-dynload/_struct.cpython-311-darwin.so'!
```

**Comment by swornimbarahi** [comment]
Fixed with
```
xcode-select --install
```
